[package]
name = "minimal_rust_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "minimal_rust_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3